-- engine/shader/init.lua — assembles shader variants from parts
--
--   local ShaderLib = require "engine.shader"
--   local shader = ShaderLib:get{ skinning = true }
--
-- LOVE builds a shader from a string, so a variant is just a different
-- concatenation. Each part (shader/parts/*.lua) supplies GLSL grouped by
-- the slot it fills, and the skeleton below is the only place the overall shape
-- of the shader is written down:
--
--   <uniforms>          declarations, one block per part
--   <functions>         helpers at file scope
--   position() {        vertex entry point
--     <calc>            each part computes what it needs
--     <mix>             each part folds its result into localPos/localNormal
--     ...fixed tail
--   }
--   effect() {          fragment entry point
--     ...fixed head
--     <calc>            each part computes what it needs
--     <mix>             each part folds its result into outColor
--   }
--
-- Why parts rather than one file per stage: a part is a FEATURE, so skinning
-- lives in exactly one place. Cutting the shader up by stage instead would
-- scatter every feature across several files and make each edit a hunt.
--
-- Variants are cached by key, so asking for the same combination twice
-- compiles once.

local PART_PATH = "engine.shader.parts."

local ShaderLib = {}
ShaderLib.__index = ShaderLib

-- Parts always present, in application order: normalmap writes shadingNormal
-- and ambientOcclusion, shadow writes shadowFactor[], pbr reads both and loops
-- over u_light*[]. Only `skinning` is optional -- see the note in its file
-- about the 2048 uniform components a bone array costs, which is the whole
-- reason variants exist.
local ALWAYS = { "normalmap", "shadow", "pbr", "fog" }

local cache = {}
local loaded = {}

local function part(name)
    if not loaded[name] then
        loaded[name] = require(PART_PATH .. name)
    end
    return loaded[name]
end

-- Collect one slot from every part, in order, skipping the parts that do not
-- fill it. Returns "" when nobody does, so the skeleton stays valid GLSL.
local function slot(parts, key)
    local out = {}
    for _, p in ipairs(parts) do
        local text = p[key]
        if text and text ~= "" then
            out[#out + 1] = ("// -- %s : %s"):format(p.name, key)
            out[#out + 1] = text
        end
    end
    return table.concat(out, "\n")
end

-- The skeleton. Everything variable is a slot; everything fixed is written
-- once, here.
local function assemble(parts)
    return table.concat({
        "// Generated by shader/init.lua -- do not edit.",
        "// Parts: " .. (function()
            local names = {}
            for _, p in ipairs(parts) do names[#names + 1] = p.name end
            return table.concat(names, ", ")
        end)(),
        "",
        -- shared by both stages
        "uniform mat4 u_viewProj;",
        "uniform mat4 u_model;",
        "uniform vec4 u_baseColor;",
        "uniform bool u_hasTexture;",
        "varying vec3 v_normal;",
        "varying vec3 v_worldPos;",
        slot(parts, "varyings"),
        "",
        "#ifdef VERTEX",
        "attribute vec3 VertexNormal;",
        slot(parts, "vertexUniforms"),
        slot(parts, "vertexFunctions"),
        "",
        "vec4 position(mat4 transform_projection, vec4 vertex_position)",
        "{",
        "    vec4 localPos = vec4(vertex_position.xyz, 1.0);",
        "    vec3 localNormal = VertexNormal;",
        "",
        slot(parts, "vertexCalc"),
        slot(parts, "vertexMix"),
        "",
        "    vec4 world = u_model * localPos;",
        "    v_normal = normalize(mat3(u_model) * localNormal);",
        -- the specular term needs a view direction, so the fragment stage has
        -- to know where in the world it sits
        "    v_worldPos = world.xyz;",
        "    return u_viewProj * world;",
        "}",
        "#endif",
        "",
        "#ifdef PIXEL",
        -- Naming this uniform MainTex is a LÖVE convention: declaring it under
        -- that exact name makes the engine auto-bind whatever texture the
        -- current draw call is using, the same texture the old effect(color,
        -- Image tex, ...) signature received as its `tex` parameter.
        "uniform Image MainTex;",
        slot(parts, "fragmentUniforms"),
        slot(parts, "fragmentFunctions"),
        "",
        -- MRT: love_Canvases[0] is the lit scene, [1] is bloom's bright-pass
        -- source. LÖVE only reads the extra target when setCanvas was actually
        -- given more than one canvas (WebGLRenderer:_renderMain sets up the
        -- pair only when bloom is on) -- with a single canvas bound it simply
        -- ignores the second write, so this shader needs no separate variant
        -- for the non-bloom path.
        "void effect()",
        "{",
        "    vec4 color = VaryingColor;",
        "    vec2 uv = VaryingTexCoord.xy;",
        "",
        -- `uv` comes from love: mesh:setTexture() binds the image and the
        -- interpolated VertexTexCoord arrives here, so no varying of ours
        "    vec4 baseColor = u_baseColor;",
        "    if (u_hasTexture) { baseColor *= Texel(MainTex, uv); }",
        "    vec4 outColor = baseColor;",
        "",
        -- The normal lighting is evaluated against. Starts as the interpolated
        -- geometric normal; a part that perturbs it (normalmap) overwrites this
        -- in its calc slot, and shading parts read it rather than v_normal, so
        -- the order in ALWAYS decides who sees what.
        "    vec3 shadingNormal = normalize(v_normal);",
        "",
        -- Scalar multiplier on the ambient term, for parts that occlude it.
        "    float ambientOcclusion = 1.0;",
        "",
        -- filled by pbr's fragmentCalc slot; bloom reads only this, not the
        -- lit result, so a bright diffuse/specular highlight does not bloom --
        -- only material-authored emissive does (see pbr.lua)
        "    vec3 _emissive = vec3(0.0);",
        "",
        slot(parts, "fragmentCalc"),
        slot(parts, "fragmentMix"),
        "",
        "    love_Canvases[0] = outColor * color;",
        "    love_Canvases[1] = vec4(_emissive, 1.0);",
        "}",
        "#endif",
    }, "\n")
end

-- opts.skinning -> include the skinning part
function ShaderLib:sourceFor(opts)
    opts = opts or {}

    local parts = {}
    if opts.skinning then parts[#parts + 1] = part("skinning") end
    for _, name in ipairs(ALWAYS) do parts[#parts + 1] = part(name) end

    return assemble(parts)
end

function ShaderLib:keyFor(opts)
    return (opts and opts.skinning) and "skinned" or "static"
end

-- Compiled variant for these options, built once and cached.
function ShaderLib:get(opts)
    local key = self:keyFor(opts)
    if cache[key] then return cache[key] end

    local source = self:sourceFor(opts)

    local ok, result = pcall(love.graphics.newShader, source)
    if not ok then
        -- A compile error here is a bug in a part, and the driver's message
        -- refers to line numbers in generated source nobody has on disk. Dump
        -- it so those numbers mean something.
        local path = ("shader_%s_failed.glsl"):format(key)
        love.filesystem.write(path, source)
        error(("shader variant '%s' failed to compile (source written to %s):\n%s")
            :format(key, love.filesystem.getSaveDirectory() .. "/" .. path, result), 0)
    end

    cache[key] = result
    return result
end

-- Drop every compiled variant, so an edited part takes effect on the next get.
function ShaderLib:reset()
    cache = {}
    loaded = {}
    return self
end

return ShaderLib
